'use strict';

// currencyCodes.js

var CurrencyCodes = module.exports = {};

CurrencyCodes.ENUM = {
    USD: { abbr: 'USD', fullName: 'United States Dollar' },

    // AED: { abbr: 'AED', fullName: 'United Arab Emirates Dirham' },
    // AFN: { abbr: 'AFN', fullName: 'Afghanistan Afghani' },
    // ALL: { abbr: 'ALL', fullName: 'Albania Lek' },
    // AMD: { abbr: 'AMD', fullName: 'Armenia Dram' },
    // ANG: { abbr: 'ANG', fullName: 'Netherlands Antilles Guilder' },
    // AOA: { abbr: 'AOA', fullName: 'Angola Kwanza' },
    // ARS: { abbr: 'ARS', fullName: 'Argentina Peso' },
    // AUD: { abbr: 'AUD', fullName: 'Australia Dollar' },
    // AWG: { abbr: 'AWG', fullName: 'Aruba Guilder' },
    // AZN: { abbr: 'AZN', fullName: 'Azerbaijan New Manat' },
    // BAM: { abbr: 'BAM', fullName: 'Bosnia and Herzegovina Convertible Marka' },
    // BBD: { abbr: 'BBD', fullName: 'Barbados Dollar' },
    // BDT: { abbr: 'BDT', fullName: 'Bangladesh Taka' },
    // BGN: { abbr: 'BGN', fullName: 'Bulgaria Lev' },
    // BHD: { abbr: 'BHD', fullName: 'Bahrain Dinar' },
    // BIF: { abbr: 'BIF', fullName: 'Burundi Franc' },
    // BMD: { abbr: 'BMD', fullName: 'Bermuda Dollar' },
    // BND: { abbr: 'BND', fullName: 'Brunei Darussalam Dollar' },
    // BOB: { abbr: 'BOB', fullName: 'Bolivia Boliviano' },
    // BRL: { abbr: 'BRL', fullName: 'Brazil Real' },
    // BSD: { abbr: 'BSD', fullName: 'Bahamas Dollar' },
    // BTN: { abbr: 'BTN', fullName: 'Bhutan Ngultrum' },
    // BWP: { abbr: 'BWP', fullName: 'Botswana Pula' },
    // BYR: { abbr: 'BYR', fullName: 'Belarus Ruble' },
    // BZD: { abbr: 'BZD', fullName: 'Belize Dollar' },
    // CAD: { abbr: 'CAD', fullName: 'Canada Dollar' },
    // CDF: { abbr: 'CDF', fullName: 'Congo/Kinshasa Franc' },
    // CHF: { abbr: 'CHF', fullName: 'Switzerland Franc' },
    // CLP: { abbr: 'CLP', fullName: 'Chile Peso' },
    // CNY: { abbr: 'CNY', fullName: 'China Yuan Renminbi' },
    // COP: { abbr: 'COP', fullName: 'Colombia Peso' },
    // CRC: { abbr: 'CRC', fullName: 'Costa Rica Colon' },
    // CUC: { abbr: 'CUC', fullName: 'Cuba Convertible Peso' },
    // CUP: { abbr: 'CUP', fullName: 'Cuba Peso' },
    // CVE: { abbr: 'CVE', fullName: 'Cape Verde Escudo' },
    // CZK: { abbr: 'CZK', fullName: 'Czech Republic Koruna' },
    // DJF: { abbr: 'DJF', fullName: 'Djibouti Franc' },
    // DKK: { abbr: 'DKK', fullName: 'Denmark Krone' },
    // DOP: { abbr: 'DOP', fullName: 'Dominican Republic Peso' },
    // DZD: { abbr: 'DZD', fullName: 'Algeria Dinar' },
    // EGP: { abbr: 'EGP', fullName: 'Egypt Pound' },
    // ERN: { abbr: 'ERN', fullName: 'Eritrea Nakfa' },
    // ETB: { abbr: 'ETB', fullName: 'Ethiopia Birr' },
    // EUR: { abbr: 'EUR', fullName: 'Euro Member Countries' },
    // FJD: { abbr: 'FJD', fullName: 'Fiji Dollar' },
    // FKP: { abbr: 'FKP', fullName: 'Falkland Islands (Malvinas) Pound' },
    // GBP: { abbr: 'GBP', fullName: 'United Kingdom Pound' },
    // GEL: { abbr: 'GEL', fullName: 'Georgia Lari' },
    // GGP: { abbr: 'GGP', fullName: 'Guernsey Pound' },
    // GHS: { abbr: 'GHS', fullName: 'Ghana Cedi' },
    // GIP: { abbr: 'GIP', fullName: 'Gibraltar Pound' },
    // GMD: { abbr: 'GMD', fullName: 'Gambia Dalasi' },
    // GNF: { abbr: 'GNF', fullName: 'Guinea Franc' },
    // GTQ: { abbr: 'GTQ', fullName: 'Guatemala Quetzal' },
    // GYD: { abbr: 'GYD', fullName: 'Guyana Dollar' },
    // HKD: { abbr: 'HKD', fullName: 'Hong Kong Dollar' },
    // HNL: { abbr: 'HNL', fullName: 'Honduras Lempira' },
    // HRK: { abbr: 'HRK', fullName: 'Croatia Kuna' },
    // HTG: { abbr: 'HTG', fullName: 'Haiti Gourde' },
    // HUF: { abbr: 'HUF', fullName: 'Hungary Forint' },
    // IDR: { abbr: 'IDR', fullName: 'Indonesia Rupiah' },
    // ILS: { abbr: 'ILS', fullName: 'Israel Shekel' },
    // IMP: { abbr: 'IMP', fullName: 'Isle of Man Pound' },
    // INR: { abbr: 'INR', fullName: 'India Rupee' },
    // IQD: { abbr: 'IQD', fullName: 'Iraq Dinar' },
    // IRR: { abbr: 'IRR', fullName: 'Iran Rial' },
    // ISK: { abbr: 'ISK', fullName: 'Iceland Krona' },
    // JEP: { abbr: 'JEP', fullName: 'Jersey Pound' },
    // JMD: { abbr: 'JMD', fullName: 'Jamaica Dollar' },
    // JOD: { abbr: 'JOD', fullName: 'Jordan Dinar' },
    // JPY: { abbr: 'JPY', fullName: 'Japan Yen' },
    // KES: { abbr: 'KES', fullName: 'Kenya Shilling' },
    // KGS: { abbr: 'KGS', fullName: 'Kyrgyzstan Som' },
    // KHR: { abbr: 'KHR', fullName: 'Cambodia Riel' },
    // KMF: { abbr: 'KMF', fullName: 'Comoros Franc' },
    // KPW: { abbr: 'KPW', fullName: 'Korea (North) Won' },
    // KRW: { abbr: 'KRW', fullName: 'Korea (South) Won' },
    // KWD: { abbr: 'KWD', fullName: 'Kuwait Dinar' },
    // KYD: { abbr: 'KYD', fullName: 'Cayman Islands Dollar' },
    // KZT: { abbr: 'KZT', fullName: 'Kazakhstan Tenge' },
    // LAK: { abbr: 'LAK', fullName: 'Laos Kip' },
    // LBP: { abbr: 'LBP', fullName: 'Lebanon Pound' },
    // LKR: { abbr: 'LKR', fullName: 'Sri Lanka Rupee' },
    // LRD: { abbr: 'LRD', fullName: 'Liberia Dollar' },
    // LSL: { abbr: 'LSL', fullName: 'Lesotho Loti' },
    // LTL: { abbr: 'LTL', fullName: 'Lithuania Litas' },
    // LVL: { abbr: 'LVL', fullName: 'Latvia Lat' },
    // LYD: { abbr: 'LYD', fullName: 'Libya Dinar' },
    // MAD: { abbr: 'MAD', fullName: 'Morocco Dirham' },
    // MDL: { abbr: 'MDL', fullName: 'Moldova Leu' },
    // MGA: { abbr: 'MGA', fullName: 'Madagascar Ariary' },
    // MKD: { abbr: 'MKD', fullName: 'Macedonia Denar' },
    // MMK: { abbr: 'MMK', fullName: 'Myanmar (Burma) Kyat' },
    // MNT: { abbr: 'MNT', fullName: 'Mongolia Tughrik' },
    // MOP: { abbr: 'MOP', fullName: 'Macau Pataca' },
    // MRO: { abbr: 'MRO', fullName: 'Mauritania Ouguiya' },
    // MUR: { abbr: 'MUR', fullName: 'Mauritius Rupee' },
    // MVR: { abbr: 'MVR', fullName: 'Maldives (Maldive Islands) Rufiyaa' },
    // MWK: { abbr: 'MWK', fullName: 'Malawi Kwacha' },
    // MXN: { abbr: 'MXN', fullName: 'Mexico Peso' },
    // MYR: { abbr: 'MYR', fullName: 'Malaysia Ringgit' },
    // MZN: { abbr: 'MZN', fullName: 'Mozambique Metical' },
    // NAD: { abbr: 'NAD', fullName: 'Namibia Dollar' },
    // NGN: { abbr: 'NGN', fullName: 'Nigeria Naira' },
    // NIO: { abbr: 'NIO', fullName: 'Nicaragua Cordoba' },
    // NOK: { abbr: 'NOK', fullName: 'Norway Krone' },
    // NPR: { abbr: 'NPR', fullName: 'Nepal Rupee' },
    // NZD: { abbr: 'NZD', fullName: 'New Zealand Dollar' },
    // OMR: { abbr: 'OMR', fullName: 'Oman Rial' },
    // PAB: { abbr: 'PAB', fullName: 'Panama Balboa' },
    // PEN: { abbr: 'PEN', fullName: 'Peru Nuevo Sol' },
    // PGK: { abbr: 'PGK', fullName: 'Papua New Guinea Kina' },
    // PHP: { abbr: 'PHP', fullName: 'Philippines Peso' },
    // PKR: { abbr: 'PKR', fullName: 'Pakistan Rupee' },
    // PLN: { abbr: 'PLN', fullName: 'Poland Zloty' },
    // PYG: { abbr: 'PYG', fullName: 'Paraguay Guarani' },
    // QAR: { abbr: 'QAR', fullName: 'Qatar Riyal' },
    // RON: { abbr: 'RON', fullName: 'Romania New Leu' },
    // RSD: { abbr: 'RSD', fullName: 'Serbia Dinar' },
    // RUB: { abbr: 'RUB', fullName: 'Russia Ruble' },
    // RWF: { abbr: 'RWF', fullName: 'Rwanda Franc' },
    // SAR: { abbr: 'SAR', fullName: 'Saudi Arabia Riyal' },
    // SBD: { abbr: 'SBD', fullName: 'Solomon Islands Dollar' },
    // SCR: { abbr: 'SCR', fullName: 'Seychelles Rupee' },
    // SDG: { abbr: 'SDG', fullName: 'Sudan Pound' },
    // SEK: { abbr: 'SEK', fullName: 'Sweden Krona' },
    // SGD: { abbr: 'SGD', fullName: 'Singapore Dollar' },
    // SHP: { abbr: 'SHP', fullName: 'Saint Helena Pound' },
    // SLL: { abbr: 'SLL', fullName: 'Sierra Leone Leone' },
    // SOS: { abbr: 'SOS', fullName: 'Somalia Shilling' },
    // SPL: { abbr: 'SPL', fullName: 'Seborga Luigino' },
    // SRD: { abbr: 'SRD', fullName: 'Suriname Dollar' },
    // STD: { abbr: 'STD', fullName: 'São Tomé and Príncipe Dobra' },
    // SVC: { abbr: 'SVC', fullName: 'El Salvador Colon' },
    // SYP: { abbr: 'SYP', fullName: 'Syria Pound' },
    // SZL: { abbr: 'SZL', fullName: 'Swaziland Lilangeni' },
    // THB: { abbr: 'THB', fullName: 'Thailand Baht' },
    // TJS: { abbr: 'TJS', fullName: 'Tajikistan Somoni' },
    // TMT: { abbr: 'TMT', fullName: 'Turkmenistan Manat' },
    // TND: { abbr: 'TND', fullName: 'Tunisia Dinar' },
    // TOP: { abbr: 'TOP', fullName: 'Tonga Pa\'anga' },
    // TRY: { abbr: 'TRY', fullName: 'Turkey Lira' },
    // TTD: { abbr: 'TTD', fullName: 'Trinidad and Tobago Dollar' },
    // TVD: { abbr: 'TVD', fullName: 'Tuvalu Dollar' },
    // TWD: { abbr: 'TWD', fullName: 'Taiwan New Dollar' },
    // TZS: { abbr: 'TZS', fullName: 'Tanzania Shilling' },
    // UAH: { abbr: 'UAH', fullName: 'Ukraine Hryvna' },
    // UGX: { abbr: 'UGX', fullName: 'Uganda Shilling' },
    // UYU: { abbr: 'UYU', fullName: 'Uruguay Peso' },
    // UZS: { abbr: 'UZS', fullName: 'Uzbekistan Som' },
    // VEF: { abbr: 'VEF', fullName: 'Venezuela Bolivar' },
    // VND: { abbr: 'VND', fullName: 'Viet Nam Dong' },
    // VUV: { abbr: 'VUV', fullName: 'Vanuatu Vatu' },
    // WST: { abbr: 'WST', fullName: 'Samoa Tala' },
    // XAF: { abbr: 'XAF', fullName: 'Communauté Financière Africaine (BEAC) CFA Franc BEAC' },
    // XCD: { abbr: 'XCD', fullName: 'East Caribbean Dollar' },
    // XDR: { abbr: 'XDR', fullName: 'International Monetary Fund (IMF) Special Drawing Rights' },
    // XOF: { abbr: 'XOF', fullName: 'Communauté Financière Africaine (BCEAO) Franc' },
    // XPF: { abbr: 'XPF', fullName: 'Comptoirs Français du Pacifique (CFP) Franc' },
    // YER: { abbr: 'YER', fullName: 'Yemen Rial' },
    // ZAR: { abbr: 'ZAR', fullName: 'South Africa Rand' },
    // ZMW: { abbr: 'ZMW', fullName: 'Zambia Kwacha' },
    // ZWD: { abbr: 'ZWD', fullName: 'Zimbabwe Dollar' }
};

CurrencyCodes.totalCount = 0;
CurrencyCodes.abbrs      = [];
for (var currencyCode in CurrencyCodes.ENUM) {
    CurrencyCodes.totalCount++;
    CurrencyCodes.abbrs.push(CurrencyCodes.ENUM[currencyCode].abbr);
}
